apiVersion: apps/v1
kind: Deployment
metadata:
  name: AuditReporter
  labels:
    app: auditreporterapp
spec:
  selector:
    matchLabels:
      app: auditreporterapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auditreporterapp
    spec:
      containers:
       —name: auditreporter
          image: x00159358/auditreporter:latest
          ports:
           —containerPort: 30022
---
apiVersion: v1
kind: Service
metadata:
  name: AuditReporter
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 30022
