apiVersion: v1
kind: Namespace
metadata:
  name: misc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditreporter
  labels:
    app: auditreporterapp
  namespace: misc
spec:
  selector:
    matchLabels:
      app: auditreporterapp
  replicas: 1
  template:
    metadata:
      labels:
        app: auditreporterapp
    spec:
      containers:
      - name: auditreporter
        image: x00159358/auditreporter:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auditreportersvc
  labels:
    svc: auditreportersvc
  namespace: misc
spec:
  selector:
    app: auditreporterapp
  ports:
    - name: auditport
      protocol: TCP
      port: 3000
      targetPort: 3000
