apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditreporter
  labels:
    app: auditreporterapp
spec:
  selector:
    matchLabels:
      app: auditreporterapp
  replicas: 1
  template:
    metadata:
      labels:
        app: auditreporterapp
    spec:
      containers:
      - name: auditreporter
        image: x00159358/auditreporter:latest
---
apiVersion: v1
kind: Service
metadata:
  name: auditreportersvc
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
