apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: audit-reporter-services
  name: audit-reporter-services
  namespace: misc
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: auditport
  namespaceSelector:
    matchNames:
    - misc
  selector:
    matchLabels:
      svc: auditreportersvc
